# Combien y a-t-il de meneurs dans l'équipe masculine de la SIG ?
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sport: <http://www.semanticweb.org/asususer/ontologies/2016/10/Sports#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT count(?meneur)
WHERE {
	?meneur a sport:Sportif;
	?meneur foaf:gender 'male'^^xsd:string;
	?meneur sport:hasClub ?club;
	?meneur sport:hasPoste ?poste.
	?club foaf:name 'SIG'^^xsd:string.
	?poste foaf:name ?nom_poste;
	FILTER(regex(?nom_poste, ".*meneur.*", "i"))
}