# Pour toutes les nationalités avec plus de 3 sportifs, nombre de ces sportifs
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sport: <http://www.semanticweb.org/asususer/ontologies/2016/10/Sports#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT count(?sportif) ?nationalite
WHERE {
	?sportif a sport:Sportif.
	?nationalite a sport:Nationalite.
	?sportif sport:hasNationality ?nationalite.
}
GROUP BY ?nationalite
HAVING (count(?sportif) > 3)