# Pour toutes les équipes, nom du club, nom de l'équipe et nom complet du capitaine s'il est connu.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sport: <http://www.semanticweb.org/asususer/ontologies/2016/10/Sports#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?equipe ?nom_club ?nom_equipe ?nom_capitaine
WHERE {
	?equipe a sport:Equipe.
	?club a sport:Club.
	?club foaf:name ?nom_club.
	?equipe foaf:name ?nom_equipe.
	OPTIONAL{
		?capitaine a sport:Sportif;
			sport:hasEquipe ?equipe;
			foaf:name ?nom_capitaine.
	}
}